title: KvDeveloper Documentation
description: Comprehensive documentation for KvDeveloper
logo: https://raw.githubusercontent.com/Novfensec/KvDeveloper/main/kvdeveloper/assets/image_library/kvdeveloper/kvdeveloper_logo256.png
baseurl: "/KvDeveloper.docs"
url: "https://novfensec.github.io"
theme: jekyll-theme-minimal

# Build settings
markdown: GFM
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# gems
gems:
  - jekyll-commonmark-ghpages
commonmark:
  options: ["smart", "footnotes", "strikethrough", "table", "tasklist"]

# Navbar configuration
header-pages:
  - index.md
  - getting-started.md
  - installation.md
  - usage.md
  - templates.md
  - commands.md
  - faqs.md

# Permalink settings
permalink: pretty

# Exclude settings
exclude:
  - Gemfile
  - Gemfile.lock
