title: KvDeveloper Documentation
description: Comprehensive documentation for KvDeveloper
baseurl: "/KvDeveloper.docs"
url: "https://novfensec.github.io"

# Build settings
markdown: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-cache
  - jekyll-seo-tag

# gems
gems:
  - jekyll-commonmark-ghpages
commonmark:
  options: ["smart", "footnotes", "strikethrough", "table", "tasklist"]

# Permalink settings
permalink: pretty

# Exclude settings
exclude:
  - Gemfile
  - Gemfile.lock
