title: KvDeveloper Documentation
description: Comprehensive documentation for KvDeveloper
baseurl: "/KvDeveloper.docs"
url: "https://novfensec.github.io"
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navbar configuration
navbar:
  - title: "Home"
    url: "/"
  - title: "Getting Started"
    url: "/getting-started/"
  - title: "Installation"
    url: "/installation/"
  - title: "Usage"
    url: "/usage/"
  - title: "Templates"
    url: "/templates/"
  - title: "Commands"
    url: "/commands/"
  - title: "FAQ"
    url: "/faq/"

# Permalink settings
permalink: pretty

# Exclude settings
exclude:
  - Gemfile
  - Gemfile.lock

# Enable relative links
relative_permalinks: true
